updated workflow file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,44 +9,72 @@ on:
       - main
 
 jobs:
-  build:
+  source:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout Code
-      uses: actions/checkout@v2
-    - name: Upload code
-      uses: actions/upload-artifact@v2
-      with:
-        name: code
-        path: .
+      - name: Checkout Code
+        uses: actions/checkout@v2
+      - name: Upload code
+        uses: actions/upload-artifact@v2
+        with:
+          name: code
+          path: .
+
+  build:
+    needs: source
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download code
+        uses: actions/download-artifact@v2
+        with:
+          name: code
+          path: .
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.10.4'
+      - name: Install dependencies
+        run: |
+          python -m venv .venv
+          source .venv/bin/activate
+          pip install --upgrade pip
+          if [ -f "./backend/requirements.txt" ]; then
+            pip install -r ./backend/requirements.txt
+          else
+            echo "Error: requirements.txt not found in ./backend"
+            exit 1
+          fi
+      - name: Upload environment and code
+        uses: actions/upload-artifact@v2
+        with:
+          name: code-and-env
+          path: |
+            .
+            .venv/
 
   test:
     needs: build
     runs-on: ubuntu-latest
     steps:
-    - name: Download code
-      uses: actions/download-artifact@v2
-      with:
-        name: code
-        path: .
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: '3.10.4'
+      - name: Download code and environment
+        uses: actions/download-artifact@v2
+        with:
+          name: code-and-env
+          path: .
+      - name: Activate virtual environment and run tests
+        run: |
+          source .venv/bin/activate
+          pytest
 
-    - name: Install dependencies
-      run: |
-        python -m venv .venv
-        source .venv/bin/activate
-        pip install --upgrade pip
-        pip install -r ./backend/requirements.txt
   # deploy:
   #   needs: test
   #   runs-on: ubuntu-latest
-  #   concurrency: test-job
   #   steps:
-  #   - name: Build Docker Image
-  #     run: |
-  #       docker build -t myapp:latest .
-
-
+  #     - name: Download code and environment
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: code-and-env
+  #         path: .
+  #     - name: Build Docker Image
+  #       run: |
+  #         docker build -t myapp:latest .
